email_address   = "emilie.clary@student.junia.com"
github_handle   = "emilieclary"
subscription_id = "8f375011-7e90-44b0-bb14-263aeaecf2ff"
enable_database      = true  # Enables the PostgreSQL database
enable_api           = true  # Enables the HTTP API
enable_storage       = true # Set this to true if you also want to enable blob storage
enable_storage_read_for_user = true
enable_storage_read_for_api  = true
allowed_ip_address = "192.168.56.1"  # Replace with the actual IP address
new_relic_licence_key = "eu01xx640899b44fb714adc66bbddf21FFFFNRAL"